"""
Server is used to create PVs and manage their lifetimes
"""

from __future__ import annotations

import logging
from abc import ABC

from p4p.client.raw import Context
from p4p.server import Server as _Server
from p4p.server import StaticProvider

from p4pillon.pvrecipe import BasePVRecipe
from p4pillon.server.raw import SharedPV

logger = logging.getLogger(__name__)


class Server(ABC):
    """
    Creates PVs and manages their lifetimes
    """

    _context = Context  # Shame we can't define an abstact class variable

    def __init__(self, prefix: str = "") -> None:
        """
        Initialize the Server instance.

        :param prefix: The prefix to be added to the PVs (Process Variables) of the server e.g. DEV: Defaults to "".
        """
        # the prefix determines the prefix of the PVs to be added to the server e.g. DEV:
        self.prefix: str = prefix  #: The prefix to be prepended to the PVs generated by this server.
        self._pvs: dict[str, SharedPV] = {}

        self._provider = StaticProvider()
        self._server: _Server | None = None

        self._running = False

        self._ctxt = Server._context("pva")

    def start(self) -> None:
        """Start the Server"""

        # iterate over all the PVs and initialise them if they haven't
        # been already, add them to the provider and start the server
        # this means that PVs are only 'opened' and given a time stamp
        # at the time the server itself is started
        for pv_name, pv in self._pvs.items():
            self._provider.add(pv_name, pv)

        self._server = _Server(providers=[self._provider])

        logger.debug("Started Server with %s", self.pvlist)

        self._running = True

    def stop(self) -> None:
        """Stop the Server"""

        # iterate over all the PVs and close them before removing them
        # from the provider and closing the server
        for pv_name, pv in self._pvs.items():
            pv.close()
            self._provider.remove(pv_name)
        if self._server:
            self._server.stop()
        logger.debug("\nStopped server")

        self._running = False

    def add_pv(self, pv_name: str, pv: BasePVRecipe | SharedPV) -> SharedPV:
        """
        Add a PV to the server

        :param pv_name: The name of the PV to be added.
        :param pv: The SharedPV or a pv recipe for creating the PV.
        :return: The created PV.
        """

        if not pv_name.startswith(self.prefix):
            pv_name = self.prefix + pv_name

        if isinstance(pv, BasePVRecipe):
            returnval = pv.create_pv(pv_name)
        else:
            returnval = pv

        self._pvs[pv_name] = returnval

        # If the server is already running then we need to add this PV to
        # the live system
        if self._running:
            self._provider.add(pv_name, returnval)
            logger.debug("Added %s to server", pv_name)

        return returnval

    def remove_pv(self, pv_name: str) -> None:
        """
        Remove a PV from the server

        :param pv_name: The name of the PV to be removed.
        :raises KeyError: If the PV is not found in the list managed by the server.
        """

        if not pv_name.startswith(self.prefix):
            pv_name = self.prefix + pv_name

        # TODO: Consider the implications if this throws an exception
        pv = self._pvs.pop(pv_name)
        pv.close()
        if self._running:
            # If the server is already running then we need to remove this PV
            # from the live system
            self._provider.remove(pv_name)
        logger.debug("Removed %s from server", pv_name)

    @property
    def pvlist(self) -> list[str]:
        """The PVs managed by the server"""
        return list(self._pvs.keys())

    def __getitem__(self, pv_name: str) -> SharedPV | None:
        """Return one of the PVs managed by the server given its name"""
        if not pv_name.startswith(self.prefix):
            pv_name = self.prefix + pv_name
        return self._pvs.get(pv_name)

    def get_pv_value(self, pv_name: str):
        """
        Get the value of a PV using SharedPV.current() if the PV is on this server
        or self._ctxt.get() if it is not.
        """
        shared_pv = self[pv_name]
        if shared_pv:
            logger.debug("Getting value using SharedPV for pv %s", pv_name)
            return shared_pv.current()

        logger.debug("Doing Context get for pv %s", pv_name)
        return self._ctxt.get(pv_name)

    def put_pv_value(self, pv_name: str, value):
        """
        Put the value to a PV using the server Context member self._ctxt
        """
        shared_pv = self[pv_name]
        if shared_pv:
            logger.debug("Trying SharedNT post to pv %s with value %r ", pv_name, value)
            shared_pv.post(value)
        else:
            logger.debug("Trying Context put to pv %s with value %r ", pv_name, value)
            self._ctxt.put(pv_name, value)
