title: p4p_ext
description: Opinionated extensions and additional functionality for the p4p library.
theme: just-the-docs

url: https://https://isisneutronmuon.github.io/p4p_ext/

aux_links: # remove if you don't want this link to appear on your pages
  GitHub Repository: https://github.com/ISISNeutronMuon/p4p_ext/


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# For copy button on code
enable_copy_code_button: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red